site_name: mlxtend
site_url:
site_description: Documentation for fast and lightweight Docker container based virtualization framework.
#include_search: true
docs_dir: sources
#theme: readthedocs
pages:
- Home: index.md

- Documentation: 
    - classifier:
        - docs/classifier/adaline.md
        - docs/classifier/perceptron.md
        - docs/classifier/logistic_regression.md
    - pandas:
        - docs/pandas/minmax_scaling.md
        - docs/pandas/standardizing.md
    - sklearn:
        - docs/sklearn/sequential_backward_selection.md
        - docs/sklearn/column_selector.md
        - docs/sklearn/ensemble_classifier.md
        - docs/sklearn/dense_transformer.md
    - evaluate:
        - docs/evaluate/plot_decision_regions.md
        - docs/evaluate/plot_learning_curves.md
    - matplotlib:
        - docs/matplotlib/category_scatter.md
        - docs/matplotlib/enrichment_plot.md
        - docs/matplotlib/stacked_barplot.md
    - regression:
        - docs/regression/plot_linear_regression_fit.md
    - preprocessing:
        - docs/preprocessing/mean_centerer.md
        - docs/preprocessing/shuffle_arrays_unison.md
    - file_io:
        - docs/file_io/find_files.md
        - docs/file_io/find_filegroups.md
    - math:
        - docs/math/combinations.md
        - docs/math/permutations.md
    - text:
        - docs/text/generalize_names.md
        - docs/text/generalize_names_duplcheck.md

- Changelog: changelog.md
- Installation: installation.md