site_name: mlxtend
site_url: http://rasbt.github.io/mlxtend
repo_url: https://github.com/rasbt/mlxtend
site_author: Sebastian Raschka
site_description: A library consisting of useful tools and extensions for the day-to-day data science tasks.
include_search: true
docs_dir: sources
#theme: readthedocs

markdown_extensions:
  - extra
  - tables
  - fenced_code
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js

pages:
- Home: index.md

- Documentation:
    - classifier:
        - md/classifier/neuralnet_mlp.md
        - md/classifier/adaline.md
        - md/classifier/perceptron.md
        - md/classifier/logistic_regression.md
        - md/classifier/scikit-learn_ensemble_classifier.md
    - feature selection:
        - md/feature_selection/sequential_backward_selection.md
        - md/feature_selection/sequential_forward_selection.md
        - md/feature_selection/sequential_floating_backward_selection.md
        - md/feature_selection/sequential_floating_forward_selection.md
        - md/feature_selection/column_selector.md
    - evaluate:
        - md/evaluate/plot_decision_regions.md
        - md/evaluate/plot_learning_curves.md
    - plotting:
        - md/plotting/category_scatter.md
        - md/plotting/enrichment_plot.md
        - md/plotting/stacked_barplot.md
    - regression:
        - md/regression/plot_linear_regression_fit.md
        - md/regression/linear_regression.md
    - preprocessing:
        - md/preprocessing/standardizing.md
        - md/preprocessing/minmax_scaling.md
        - md/preprocessing/mean_centerer.md
        - md/preprocessing/shuffle_arrays_unison.md
        - md/preprocessing/scikit-learn_dense_transformer.md
    - file_io:
        - md/file_io/find_files.md
        - md/file_io/find_filegroups.md
    - math:
        - md/math/combinations.md
        - md/math/permutations.md
    - text:
        - md/text/generalize_names.md
        - md/text/generalize_names_duplcheck.md
        - md/text/tokenizer.md
    - data:
        - md/data/iris.md
        - md/data/wine.md
        - md/data/autompg.md
        - md/data/mnist.md

- Changelog: changelog.md
- Installation: installation.md
- Contributing: contributing.md
